name: Run Behave Tests with Allure Report

on:
  push:
    branches:
      - main  # or 'master' based on your repo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-behave

      # 4. Run Behave Tests with Allure formatter
      - name: Run Behave Tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results

      # 5. Upload Allure Results to GitHub Artifact
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/allure-results
